# Keycloak realm variables
variable "realm_name" {
  description = "Name of the Keycloak realm"
  type        = string
}

variable "enabled" {
  description = "Whether the realm is enabled"
  type        = bool
  default     = true
}

variable "display_name" {
  description = "Display name of the realm"
  type        = string
  default     = null
}

variable "display_name_html" {
  description = "HTML display name of the realm"
  type        = string
  default     = null
}

# Login settings
variable "registration_allowed" {
  description = "Whether user registration is allowed"
  type        = bool
  default     = true
}

variable "registration_email_as_username" {
  description = "Whether email is used as username for registration"
  type        = bool
  default     = false
}

variable "remember_me" {
  description = "Whether remember me is enabled"
  type        = bool
  default     = true
}

variable "verify_email" {
  description = "Whether email verification is required"
  type        = bool
  default     = false
}

variable "login_with_email_allowed" {
  description = "Whether login with email is allowed"
  type        = bool
  default     = false
}

variable "duplicate_emails_allowed" {
  description = "Whether duplicate emails are allowed"
  type        = bool
  default     = true
}

variable "reset_password_allowed" {
  description = "Whether password reset is allowed"
  type        = bool
  default     = true
}

variable "edit_username_allowed" {
  description = "Whether username editing is allowed"
  type        = bool
  default     = false
}

# Session settings
variable "sso_session_idle_timeout" {
  description = "SSO session idle timeout in seconds"
  type        = number
  default     = 1800
}

variable "sso_session_max_lifespan" {
  description = "SSO session max lifespan in seconds"
  type        = number
  default     = 36000
}

variable "offline_session_idle_timeout" {
  description = "Offline session idle timeout in seconds"
  type        = number
  default     = 2592000
}

variable "offline_session_max_lifespan" {
  description = "Offline session max lifespan in seconds"
  type        = number
  default     = 5184000
}

variable "offline_session_max_lifespan_enabled" {
  description = "Whether offline session max lifespan is enabled"
  type        = bool
  default     = false
}

# Token settings
variable "access_token_lifespan" {
  description = "Access token lifespan in seconds"
  type        = number
  default     = 300
}

variable "access_token_lifespan_for_implicit_flow" {
  description = "Access token lifespan for implicit flow in seconds"
  type        = number
  default     = 900
}

variable "access_code_lifespan" {
  description = "Access code lifespan in seconds"
  type        = number
  default     = 60
}

variable "access_code_lifespan_user_action" {
  description = "Access code lifespan for user action in seconds"
  type        = number
  default     = 300
}

variable "access_code_lifespan_login" {
  description = "Access code lifespan for login in seconds"
  type        = number
  default     = 1800
}

variable "action_token_generated_by_admin_lifespan" {
  description = "Action token generated by admin lifespan in seconds"
  type        = number
  default     = 43200
}

variable "action_token_generated_by_user_lifespan" {
  description = "Action token generated by user lifespan in seconds"
  type        = number
  default     = 300
}

# Security settings
variable "ssl_required" {
  description = "SSL requirement level"
  type        = string
  default     = "external"
  validation {
    condition     = contains(["all", "external", "none"], var.ssl_required)
    error_message = "SSL required must be one of: all, external, none."
  }
}

variable "brute_force_protected" {
  description = "Whether brute force protection is enabled"
  type        = bool
  default     = false
}

variable "permanent_lockout" {
  description = "Whether permanent lockout is enabled"
  type        = bool
  default     = false
}

variable "max_failure_wait_seconds" {
  description = "Maximum failure wait time in seconds"
  type        = number
  default     = 900
}

variable "minimum_quick_login_wait_seconds" {
  description = "Minimum quick login wait time in seconds"
  type        = number
  default     = 60
}

variable "wait_increment_seconds" {
  description = "Wait increment in seconds"
  type        = number
  default     = 60
}

variable "quick_login_check_millis" {
  description = "Quick login check time in milliseconds"
  type        = number
  default     = 1000
}

variable "max_delta_time_seconds" {
  description = "Maximum delta time in seconds"
  type        = number
  default     = 43200
}

variable "failure_factor" {
  description = "Failure factor"
  type        = number
  default     = 30
}

# Token refresh settings
variable "revoke_refresh_token" {
  description = "Whether to revoke refresh tokens"
  type        = bool
  default     = false
}

variable "refresh_token_max_reuse" {
  description = "Maximum refresh token reuse count"
  type        = number
  default     = 0
}

# Additional attributes
variable "attributes" {
  description = "Additional realm attributes"
  type        = map(string)
  default     = {}
}

# Common variables (inherited from common.hcl)
variable "tags" {
  description = "Common tags to apply to all resources"
  type        = map(string)
  default     = {}
}