spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/keycloak_forge}
    username: ${DATABASE_USERNAME:forge_user}
    password: ${DATABASE_PASSWORD:forge_password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC

  cache:
    type: simple

  data:
    redis:
      url: ${REDIS_URL:redis://localhost:6379}
      timeout: 2000ms
      connect-timeout: 5000ms

server:
  port: 8080
  servlet:
    context-path: /

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
      show-components: always

logging:
  level:
    com.keycloak.forge: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Keycloak configuration
keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8090}
  admin:
    username: ${KEYCLOAK_ADMIN_USERNAME:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
    client-id: admin-cli
    realm: master

# Application configuration
app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:8080
  cache:
    enabled: true
    default-ttl: 3600
  security:
    jwt:
      enabled: false  # Disabled for development
    rate-limit:
      enabled: false  # Disabled for development
  conversion:
    max-file-size: 50MB
    timeout: 300000  # 5 minutes
    batch-size: 10
