// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pqsburxhkxlltucuzkvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBxc2J1cnhoa3hsbHR1Y3V6a3ZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDU3MDYsImV4cCI6MjA2NTU4MTcwNn0.RCbarpbjpChqmnbXqy4O3sf8ngDRX0G7cnuiayJwFRA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);